Fruits_World/Controllers/DuyenPD/Admin_EditAccountController.cs
using Fruits_World.Models;
using FruitsWorld.Models;
using Microsoft.AspNetCore.Mvc;
using Fruits_World.Models.DuyenPD.DAO;

namespace Fruits_World.Controllers.DuyenPD
{
    public class Admin_EditAccountController : Controller
    {
        AccountDAO dao = new AccountDAO();
        DecentralizationDAO phanquyen = new DecentralizationDAO();

        //controller lấy danh sách toàn bộ account
        public IActionResult admin_EditAccount()
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isAdmin(role))
            {
                return NotFound();
            }

            var list = dao.getAllAccount();
            return View(list);
        }

        //update info acc
        public IActionResult admin_UpdateInformation(string? id)
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isAdmin(role))
            {
                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }
            var infor = dao.getAccountbyID(id);
            return View(infor);
        }

        //Post: các thông tin đã nhập phù hợp thì chỉnh sửa thông tin account đó
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult admin_UpdateInformation(string? id, Account account)
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isAdmin(role))
            {
                return NotFound();
            }

            if (id != account.id_Account)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                dao.updateInformation(account);
                return RedirectToAction("admin_EditAccount");
            }
            return View(account);
        }

        //controller xoá  account theo id
        public IActionResult deleteAccount(int id)
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isAdmin(role))
            {
                return NotFound();
            }
            dao.deleteAccount(id);
            return RedirectToAction("admin_EditAccount");
        }


    }
}

Fruits_World/Views/Admin_EditAccount/admin_EditAccount.cshtml
@model IEnumerable<FruitsWorld.Models.Account>

@{
    ViewData["Title"] = "Danh sách tài khoản";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<div class="page">
    <h1 class="page__title">Thông tin khách hàng</h1>
    <table class="layout display responsive-table">
        <thead>
            <tr>
                <th>Avt</th>
                <th>username</th>
                <th>Tên khách hàng</th>
                <th>Năm sinh</th>
                <th>SDT</th>
                <th>Địa chỉ</th>
                <th>Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="organisationnumber">
                        <img src="@item.avatar" style="width: 50px; height:50px">
                    </td>
                    <td class="organisationnumber">@item.username</td>
                    <td class="organisationnumber">@item.fullName</td>
                    <td class="organisationnumber">@item.birth</td>
                    <td class="organisationnumber">@item.sdt</td>
                    <td class="organisationnumber">@item.address</td>
                    @*<td class="organisationnumber">@item.id_Role</td>*@
                    <td class="organisationnumber">
                        <a class="a-success"  href="/Admin_EditAccount/admin_UpdateInformation/@item.id_Account">Chỉnh sửa</a> |
                        
                        <a class="a-cancel" href="#" onclick="showMess(@item.id_Account)" >Xoá</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<script>
    function showMess(id) {
        var option = confirm("Bạn có chắc muốn xóa Tài Khoản này?");
        if (option === true) {
            window.location.href = '/Admin_EditAccount/deleteAccount?id='+id;
        }

    }
</script>

Fruits_World/Views/Admin_EditAccount/admin_UpdateInformation.cshtml
@model FruitsWorld.Models.Account

@{
    ViewData["Title"] = "Chỉnh sửa thông tin khách hàng";
}

<h1>Edit</h1>

<h4>@ViewBag.Mess</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="admin_UpdateInformation" asp-controller="Admin_EditAccount" onsubmit="return checkAllData()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label hidden asp-for="id_Account" class="control-label"></label>
                <input type="hidden" asp-for="id_Account" class="form-control" />
                <span asp-validation-for="id_Account" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="username" class="control-label">Tài khoản</label>
                <input asp-for="username" class="form-control" readonly />
                <span asp-validation-for="username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fullName" class="control-label">Họ và tên</label>
                <input id="txtFullName" asp-for="fullName" class="form-control" onblur="checkFullname()" />
                <span id="txtFullNameError" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="birth" class="control-label"></label>
                <input id="txtBirth" asp-for="birth" class="form-control" onblur="checkBirth()" />
                <span id="txtBirthError" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sdt" class="control-label"></label>
                <input id="txtSdt" asp-for="sdt" class="form-control" onblur="checkPhone()" />
                <span id="txtSdtError" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input id="txtAddress" asp-for="address" class="form-control" onblur="checkAddress()" />
                <span id="txtAddressError" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="accountInformation" asp-controller="Account_Information">Trở về</a>
</div>

<script type="text/javascript">
    var patt_phone = /^0[1-9]\d{8,9}$/;
    var patt_username = /^[a-zA-Z0-9]+$/

        function checkFullname() {
            tk = document.getElementById("txtFullName").value;
            document.getElementById("txtFullNameError").innerHTML = tk.trim() == "" ? "Họ và tên không được để trống!" : "";
            return tk != "" ? true : false;
        }
         function checkBirth() {
            birth = document.getElementById("txtBirth").value;
            if(birth > 1900 && birth < 2023){
                document.getElementById("txtBirthError").innerHTML = "";
                return true;
            }else if(birth.trim()==""){
                document.getElementById("txtBirthError").innerHTML = "Năm sinh không được để trống";
                return false;
            } else{
                document.getElementById("txtBirthError").innerHTML = "Năm sinh phải lớn hơn 1900 và nhỏ hơn 2023!";
                return false;
            }
        }
        function checkAddress() {
            address = document.getElementById("txtAddress").value;
            document.getElementById("txtAddressError").innerHTML = address.trim() == "" ? "Địa chỉ không được để trống!" : "";
            return address != "" ? true : false;
        }
        function checkPhone() {
            phone = document.getElementById("txtSdt").value;
            if(phone.trim() == ""){
                document.getElementById("txtSdtError").innerHTML = "Số điện thoại không được để trống!";
            }else if(patt_phone.test(phone)== false){
                document.getElementById("txtSdtError").innerHTML = "Định dạng số điện thoại không đúng! (bắt đầu từ 0 và phải 10-11 kí tự!)";
            }else{
                document.getElementById("txtSdtError").innerHTML = "";
                return true;
            }
            return false;
        }

        function checkAllData() {
            isValidFullname = checkFullname();
            isvalidBirth = checkBirth();
            isValidPhone = checkPhone();
            isValidAddress = checkAddress();
            isValid = isValidFullname && isvalidBirth && isValidPhone && isValidAddress;
            return isValid;
        }
</script>
@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}