Fruits_World/Models/Entity/Feedback.cs
using FruitsWorld.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fruits_World.Models.Entity
{
    public class Feedback
    {
        public string? id_Account { get; set; }
        public string? id_Product { get; set; }
        public int? stars { get; set; }
        public string? content { get; set; }
        public DateTime? date { get; set; }
    }
}

Fruits_World/Controllers/DuyenPD/FeedbackProductController.cs
using Fruits_World.Models.DuyenPD.DAO;
using Microsoft.AspNetCore.Mvc;

namespace Fruits_World.Controllers.DuyenPD
{
    public class FeedbackProductController : Controller
    {
        FeedbackDAO feedbackDAO = new FeedbackDAO();
        DecentralizationDAO phanquyen = new DecentralizationDAO();

        //lấy thông tin product để cho người dùng đánh giá
        public IActionResult Feedback(string idBill, string idPro)
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isLogin(role))
            {
                return NotFound();
            }

            if (idBill == null || idPro == null)
            {
                return NotFound();
            }
            ViewBag.IdBill = idBill;
            ViewBag.IdPro = idPro;
            return View();
        }


        //lấy thông tin đánh giá product từ khách hàng
        [HttpPost]
        public IActionResult Feedback(string idBill, string idPro, int starts, string content)
        {
            if (idBill == null || idPro == null || content == null)
            {
                return NotFound();
            }
            if (starts < 1 || starts > 5)
            {
                return NotFound();
            }
            string start = "" + starts;
            string idAcc = HttpContext.Session.GetString("id");
            if (idAcc == null)
            {
                return NotFound();
            }

            feedbackDAO.FeedbackProduct(idAcc, idBill, idPro, start, content);

            return RedirectToAction("Order_ReceivedProduct","Order_Show");
        }
    }
}

Fruits_World/Views/FeedbackProduct/Feedback.cshtml
@using FruitsWorld.Models
@using Fruits_World.Models.DuyenPD.DAO
@{
    ViewData["Title"] = "Đánh giá sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ProductDAO productDAO = new ProductDAO();
    AccountDAO accountDAO = new AccountDAO();
    Product product = productDAO.getProductbyId(ViewBag.IdPro);
    Account account = accountDAO.getAccountbyID(product.id_Account);
}





<div class="Cart_product">
    <div class="Cart_product-title">
        <h2 class="Cart_title">Đánh giá</h2>
    </div>


    <!-- Cart-product -->
    <div class="GioHang">

        <div class="Cart_product-headding">
            <div class="check_box-sp1">@account.fullName <i class="fa-brands fa-rocketchat"></i></div>
        </div>
        <div class="Cart_product-list1">
            <div class="check_box-sp1">
                <div class="check_info-item">
                    <div class="check_img">
                        <div class="check_avata">
                            <img src="@product.productImage" class="check_avata-product">
                        </div>
                    </div>
                    <div class="check_info">
                        <div href="" class="check_info-title">@product.productName</div>
                    </div>
                </div>
            </div>

        </div>
        <div class="startss">
            <form asp-action="Feedback" asp-controller="FeedbackProduct" method="post" class="start-itme">
                <div class="stars-move">
                    <input hidden value=@ViewBag.IdBill name="idBill" />
                    <input hidden value=@ViewBag.IdPro name="idPro" />
                    <input value="5" class="star star-5" id="star-5" type="radio" name="starts" />
                    <label class="star star-5" for="star-5"></label>
                    <input value="4" class="star star-4" id="star-4" type="radio" name="starts" />
                    <label class="star star-4" for="star-4"></label>
                    <input value="3" class="star star-3" id="star-3" type="radio" name="starts" />
                    <label class="star star-3" for="star-3"></label>
                    <input value="2" class="star star-2" id="star-2" type="radio" name="starts" />
                    <label class="star star-2" for="star-2"></label>
                    <input value="1" class="star star-1" id="star-1" type="radio" name="starts" />
                    <label class="star star-1" for="star-1"></label>
                </div>
                <div class="product__text-item">
                    <input class="product__text-comment" name="content" type="text" placeholder="Hãy chia sẽ những gì bạn thích về sản phẩm này nhé">
                    <div class="product__text-icon">
                        <button type="submit" class="btn"><i class="fa-solid fa-square-caret-right"></i></button>
                    </div>
                </div>

            </form>
        </div>

    </div>






</div>