Fruits_World/Controllers/SonNN/Product_CheckOutController.cs
using Fruits_World.Models.SonNN.DAO;
using FruitsWorld.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fruits_World.Controllers.SonNN
{
    public class Product_CheckOutController : Controller
    {
        Models.DuyenPD.DAO.DecentralizationDAO phanquyen = new Models.DuyenPD.DAO.DecentralizationDAO();
        ProductDAO ProductDAO = new ProductDAO();

        //Hiển thị những sản phẩm chuẩn bị thanh toán
        public IActionResult checkOut_Show()
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isLogin(role))
            {
                return NotFound();
            }

            ProductDAO Productdao = new ProductDAO();
            CartDAO Cartdao = new CartDAO();
            List<string> listnotEnoughProduct = new List<string>();
            string idAccount = HttpContext.Session.GetString("id");
            List<Account> listName = Cartdao.getAllShopIDForCart(idAccount);
            List<Cart> list = null;
            ViewBag.NotEnoughInformation = TempData["NotEnoughInformation"];
            foreach (Account a in listName)
            {
                list = Cartdao.getAllCart(idAccount, a.id_Account);
                foreach (Cart cart in list)
                {
                    Product product = Productdao.getProductbyId(cart.id_Product);
                    if (cart.quantity > product.productQuantity)
                    {
                        listnotEnoughProduct.Add(product.productName);
                    }

                }
            }
            if (listnotEnoughProduct.Count > 0)
            {
                TempData["listMessage"] = listnotEnoughProduct;
                return RedirectToAction("Cart_Show", "Cart_Manage");

            }

            ViewBag.PayFail = TempData["PayFail"];
            return View();
        }
        //Thanh toán những sản phẩm trong giỏ hàng
        public IActionResult checkOut_Pay(string? phuongthucthanhtoan, string address, string sdt, string fullname)
        {
            int? role = HttpContext.Session.GetInt32("role");
            if (!phanquyen.isLogin(role))
            {
                return NotFound();
            }

            CartDAO Cartdao = new CartDAO();
            ProductDAO Productdao = new ProductDAO();
            AccountDAO accountDAO = new AccountDAO();
            String idAccount = HttpContext.Session.GetString("id");
            List<Account> listName = Cartdao.getAllShopIDForCart(idAccount);
            List<Cart> list = null;
            TempData["address"] = address;
            TempData["sdt"] = sdt;
            TempData["fullname"] = fullname;
            if (address.Equals("0") || sdt.Equals("0"))
            {
                TempData["NotEnoughInformation"] = "Qúy khách cần nhập địa chỉ và số điện thoại để tiến hành đặt hàng";
                return RedirectToAction("checkOut_Show");
            }

            if (phuongthucthanhtoan.Equals("1"))
            {

                foreach (Account a in listName)
                {
                    list = Cartdao.getAllCart(idAccount, a.id_Account);
                    Cartdao.payCart(idAccount, a.id_Account, phuongthucthanhtoan, list);
                    accountDAO.InsertNotification(a.id_Account, "Bạn có đơn hàng đang chờ xác nhận");

                }
            }
            else if (phuongthucthanhtoan.Equals("2"))
            {
                Account account = accountDAO.getAccountbyID(idAccount);
                int cartPrice = Cartdao.getPriceforCart(idAccount);
                if (account.money < cartPrice)
                {

                    TempData["PayFail"] = "Ví điện tử của quý khách có số dư không đủ! hãy nạp thêm tiền hoặc chọn thanh toán trực tiếp";
                    return RedirectToAction("checkOut_Show");

                }
                else
                {
                    foreach (Account a in listName)
                    {
                        list = Cartdao.getAllCart(idAccount, a.id_Account);
                        Cartdao.payCart(idAccount, a.id_Account, phuongthucthanhtoan, list);
                        accountDAO.InsertNotification(a.id_Account, "Bạn có đơn hàng đang chờ xác nhận");

                    }
                    accountDAO.updateMoney(idAccount, -cartPrice);
                }
            }



            return RedirectToAction("Cart_Success", "Cart_Manage");
        }
        // hiển thị sản phẩm mua ngay
        public IActionResult checkOut_MuaNgay(string idsp, string soluong)
        {
            Product product = ProductDAO.getProductbyId(idsp);
            ViewBag.soluong = soluong;

            return View(product);
        }
        //thanh toán sản phẩm đã chọn
        public IActionResult checkOut_PayMuaNgay(string address, string sdt, string? phuongthucthanhtoan, string productid, string soluong, string tong)
        {
            List<Cart> list = new List<Cart>();
            CartDAO cartDAO = new CartDAO();
            ProductDAO productDAO = new ProductDAO();
            String idAccount = HttpContext.Session.GetString("id");
            AccountDAO accountDAO = new AccountDAO();
            Product product = productDAO.getProductbyId(productid);
            List<string> listnotEnoughProduct = new List<string>();

            if (address.Equals("0") || sdt.Equals("0"))
            {
                TempData["NotEnoughInformation"] = "Qúy khách cần nhập địa chỉ và số điện thoại để tiến hành đặt hàng";
                return RedirectToAction("accountInformation", "Account_Information");
            }
            if (phuongthucthanhtoan.Equals("2"))
            {
                list.Add(new Cart
                {
                    id_Account = idAccount,
                    id_Product = productid,
                    quantity = Convert.ToInt32(soluong)
                });
                cartDAO.payCartMuaNgay(idAccount, product.id_Account, phuongthucthanhtoan, list);
                accountDAO.InsertNotification(product.id_Account, "Bạn có đơn hàng đang chờ xác nhận");

            }
            else if (phuongthucthanhtoan.Equals("1"))
            {
                Account account = accountDAO.getAccountbyID(idAccount);
                if (account.money < Convert.ToInt32(tong))
                {

                    TempData["PayFail"] = "Ví điện tử của quý khách có số dư không đủ! hãy nạp thêm tiền hoặc chọn thanh toán trực tiếp";
                    return RedirectToAction("accountInformation", "Account_Information");


                }
                else
                {
                    list.Add(new Cart
                    {
                        id_Account = idAccount,
                        id_Product = productid,
                        quantity = Convert.ToInt32(soluong)
                    });
                    cartDAO.payCart(idAccount, product.id_Account, phuongthucthanhtoan, list);
                    accountDAO.InsertNotification(product.id_Account, "Bạn có đơn hàng đang chờ xác nhận");


                    accountDAO.updateMoney(idAccount, -Convert.ToInt32(tong));
                }
            }
            return RedirectToAction("Cart_Success", "Cart_Manage");
        }

    }
}

Fruits_World/Views/Product_CheckOut/checkOut_MuaNgay.cshtml
@using FruitsWorld.Models
@using Fruits_World.Models.SonNN.DAO
@model FruitsWorld.Models.Product
@using Microsoft.AspNetCore.Http
@using System.Globalization
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Đặt hàng - mua ngay";
    ProductDAO Productdao = new ProductDAO();
    AccountDAO accountDAO = new AccountDAO();
    Account account = accountDAO.getAccountbyID(@HttpContextAccessor.HttpContext.Session.GetString("id"));
    Product product = Productdao.getProductbyId(Model.id_Product);
    Account Shopaccount = accountDAO.getAccountbyID(Model.id_Account);
    int sum = Convert.ToInt32(ViewBag.soluong) * product.productPrice;
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
    string Price = double.Parse(Model.productPrice.ToString()).ToString("#,###", cul.NumberFormat);
    string SumPrice = double.Parse(sum.ToString()).ToString("#,###", cul.NumberFormat);

}
<h1>@ViewBag.PayFail</h1>
<h1>@ViewBag.NotEnoughInformation</h1>
<h1>@ViewBag.loi</h1>
<div class="Cart_product">

    <div class="Cart_product-title">
        <h2 class="Cart_title">Thanh toán</h2>
    </div>

    <div class="cart_adress">
        <div class="info__address-line"></div>
        <div class="info__address-items">
            <div class="info__address-headding">
                <div class="info__logo"><i class="fa-solid fa-location-dot"></i></div>
                <div class="info__adress-cus">Địa chỉ nhận hàng</div>
            </div>
        </div>

        <div class="info__address">
            <div class="info__address-form">
                <div class="info__sdt">@account.fullName @account.sdt</div>
                <div class="info_form">@account.address</div>
                <a href="/AccOunt_UpdateInformation/account_UpdateInformation/@account.id_Account"><div class="info_trangthai">Thay đổi</div></a>
            </div>
        </div>
    </div>
    <!-- end list -->
    <!-- Cart-product -->

    <div class="GioHang">
            <div class="Cart_product-headding">
                <lable class="check_box">

                </lable>

                <div class="check_box-sp1">@Shopaccount.fullName <i class="fa-brands fa-rocketchat"></i></div>
            </div>
            <div class="list-item">
                    <div class="Cart_product-list1">
                        <lable class="check_box">

                        </lable>

                        <div class="check_box-sp">
                            <div class="check_info-item">
                                <div class="check_img">
                                    <a href="#" class="check_avata">
                                        <img src="@product.productImage" class="check_avata-product">
                                    </a>
                                </div>
                                <div class="check_info">
                                    <a href="" class="check_info-title">@product.productName</a>
                                </div>
                            </div>
                        </div>
                        <div class="check_box-dg">
                            <div class="check_dongia">
                                <span class="giacu">100.000 vnd </span>
                                <span class="giamoi">@Price vnd </span>
                            </div>
                        </div>
                        <div class="check_box-sl">
                            <ul>
                                <li>
                                    <div class="nut_soluong">
                                        <p>@ViewBag.soluong</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="check_box-st">@SumPrice vnd</div>
                    </div>
            </div>



        <!-- Phuong thuc thanh toan  -->
        <form asp-action="checkOut_PayMuaNgay" asp-controller="Product_CheckOut" onsubmit="return checkPttt()">
            <div class="ThanhToan">
                <div class="ThanhToan__item">
                    <label for="" class="ThanhToan__nao">Phương thức thanh toán:</label>
                    <input type="hidden" name="address" value="@account.address"/>
                    <input type="hidden" name="sdt" value="@account.sdt"/>
                    <input type="hidden" name="productid" value="@Model.id_Product"/>
                    <input type="hidden" name="soluong" value="@ViewBag.soluong"/>
                    <input type="hidden" name="tong" value="@sum"/>
                    <br>
                    <input id="atm" class="check_radio" name="phuongthucthanhtoan" type="radio" value="2" /><label for="atm">Thẻ tín dụng</label>
                    <input  id="tienMat" class="check_radio" name="phuongthucthanhtoan" type="radio" value="1" /><label for="tienMat">Thanh toán khi nhận hàng</label>
                    <span style="color:red" id="txtError"></span>
                </div>
            </div>

            <!-- end thanh toan -->
            <!-- cart-footer -->
            <div class="Cart_product-footers">
                <div class="Cart_produc-items">

                    <div class="check_box-sl1">Tổng thanh toán :</div>
                    <div class="check_box-sl1">@SumPrice vnd</div>

                    <div class="check_box-tt">
                        <input type="submit" class="btn" value="Đặt hàng" />
                    </div>

                </div>
            </div>
        </form>
        <!-- end-footter -->
    </div>




</div>

<script>
    function checkPttt() {
        var check = document.getElementsByName("phuongthucthanhtoan");
        if (check[0].checked == false && check[1].checked == false) {
            document.getElementById("txtError").innerHTML = "     Vui lòng chọn phương thức thanh toán!";
            return false;
        }
        return true;
    }

</script>

Fruits_World/Views/Product_CheckOut/checkOut_Show.cshtml
@using FruitsWorld.Models
@using Fruits_World.Models.SonNN.DAO
@model IEnumerable<FruitsWorld.Models.Cart>
@using Microsoft.AspNetCore.Http
@using System.Globalization
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Đặt hàng - giỏ hàng";
    CartDAO Cartdao = new CartDAO();
    ProductDAO Productdao = new ProductDAO();
    AccountDAO accountDAO = new AccountDAO();
    List<Account> listName = Cartdao.getAllShopIDForCart(@HttpContextAccessor.HttpContext.Session.GetString("id"));
    List<Cart> list = null;
    int? sum = 0;
    int? sumAll = 0;
    Account account = accountDAO.getAccountbyID(@HttpContextAccessor.HttpContext.Session.GetString("id"));
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");
    string sumAllPrice = "";
}
<h1 style="color:red;">@ViewBag.PayFail</h1>
<h1>@ViewBag.NotEnoughInformation</h1>
<div class="Cart_product">

    <div class="Cart_product-title">
        <h2 class="Cart_title">Thanh toán</h2>
    </div>

    <div class="cart_adress">
        <div class="info__address-line"></div>
        <div class="info__address-items">
            <div class="info__address-headding">
                <div class="info__logo"><i class="fa-solid fa-location-dot"></i></div>
                <div class="info__adress-cus">Địa chỉ nhận hàng</div>
            </div>
        </div>

        <div class="info__address">
            <div class="info__address-form">
                <div class="info__sdt">@account.fullName @account.sdt</div>
                <div class="info_form">@account.address</div>
                <a href="/AccOunt_UpdateInformation/account_UpdateInformation/@account.id_Account"><div style="text-decoration : none;" class="info_trangthai">Thay đổi</div></a>
            </div>
        </div>
    </div>

 
    <!-- end list -->
    <!-- Cart-product -->

    <div class="GioHang">
        @foreach (Account a in listName)
        {
            <div class="Cart_product-headding">
                <lable class="check_box">

                </lable>

                <div class="check_box-sp1">@a.fullName <i class="fa-brands fa-rocketchat"></i></div>
            </div>
            list = Cartdao.getAllCart(@HttpContextAccessor.HttpContext.Session.GetString("id"), @a.id_Account);
            <div class="list-item">
                @foreach (Cart cart in list)
                {
                    Product product = Productdao.getProductbyId(cart.id_Product);
                    sum = 0;
                    sum = cart.quantity * product.productPrice;
                    sumAll = sumAll + sum;
                    string price = double.Parse(product.productPrice.ToString()).ToString("#,###", cul.NumberFormat);
                    string sumPrice = double.Parse(sum.ToString()).ToString("#,###", cul.NumberFormat);
                     sumAllPrice = double.Parse(sumAll.ToString()).ToString("#,###", cul.NumberFormat);
                    <div class="Cart_product-list1">
                        <lable class="check_box">

                        </lable>

                        <div class="check_box-sp">
                            <div class="check_info-item">
                                <div class="check_img">
                                    <a href="#" class="check_avata">
                                        <img src="@product.productImage" class="check_avata-product">
                                    </a>
                                </div>
                                <div class="check_info">
                                    <a href="" class="check_info-title">@product.productName</a>
                                </div>
                            </div>
                        </div>
                        <div class="check_box-dg">
                            <div class="check_dongia">
                                <span class="giacu">100.000 vnd </span>
                                <span class="giamoi">@price vnd </span>
                            </div>
                        </div>
                        <div class="check_box-sl">
                            <ul>
                                <li>
                                    <div class="nut_soluong">
                                        <p>@cart.quantity</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="check_box-st">@sumPrice vnd</div>
                    </div>


                }
            </div>


        }
        <!-- Phuong thuc thanh toan  -->
        <form asp-action="checkOut_Pay" asp-controller="Product_CheckOut" onsubmit="return checkPttt()">
            <div class="ThanhToan">
                <div class="ThanhToan__item">
                    <label for="" class="ThanhToan__nao">Phương thức thanh toán:</label>
                    <input type="hidden" name="address" value="@account.address"/>
                    <input type="hidden" name="sdt" value="@account.sdt"/>
                    <input type="hidden" name="fullname" value="@account.fullName"/>
                    <br>
                    <input id="atm" class="check_radio" name="phuongthucthanhtoan" type="radio" value="2" /><label for="atm"> Thẻ tín dụng</label>
                    <input id="tienMat" class="check_radio" name="phuongthucthanhtoan" type="radio" value="1" /><label for="tienMat"> Thanh toán khi nhận hàng</label> 
                    <span style="color:red" id="txtError"></span>
                </div>
            </div>

            <!-- end thanh toan -->
            <!-- cart-footer -->
            <div class="Cart_product-footers">
                <div class="Cart_produc-items">

                    <div class="check_box-sl1">Tổng thanh toán :</div>
                    <div class="check_box-sl1">@sumAllPrice vnd</div>

                    <div class="check_box-tt">
                        <input type="submit" class="btn" value="Đặt hàng" />
                    </div>

                </div>
            </div>
        </form>
        <!-- end-footter -->
    </div>




</div>

<script>
    function checkPttt() {
        var check = document.getElementsByName("phuongthucthanhtoan");
        if (check[0].checked == false && check[1].checked == false) {
            document.getElementById("txtError").innerHTML = "     Vui lòng chọn phương thức thanh toán!";
            return false;
        }
        return true;
    }

</script>